### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by ravening** [jalibu/MMM-Jast#31]
### Node.js Version

v10.16.0

### MagicMirror Version

v2.8.0

### Module Version

v2.8.0

### Description

Seeing this error message in log.

```
0|MagicMirror  | App threw an error during load
0|MagicMirror  | TypeError: i.log is not a function
0|MagicMirror  |     at Class.start (/home/pi/MagicMirror/modules/MMM-Jast/node_helper.js:29:462)
0|MagicMirror  |     at /home/pi/MagicMirror/js/app.js:225:18
0|MagicMirror  |     at new Server (/home/pi/MagicMirror/js/server.js:74:3)
0|MagicMirror  |     at /home/pi/MagicMirror/js/app.js:218:18
0|MagicMirror  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:167:5)
0|MagicMirror  |     at /home/pi/MagicMirror/js/app.js:162:6
0|MagicMirror  |     at Class.loaded (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:19:3)
0|MagicMirror  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|MagicMirror  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:160:5)
0|MagicMirror  |     at /home/pi/MagicMirror/js/app.js:162:6
```

### Steps to reproduce

1. start mmm
2. it doesnt load anything because of the exception

### config.js

```javascript
usign the basic config file which is mentioned in the readme file
```

**Comment by jalibu** [comment]
did you run npm install in the MMM-Jast folder?

**Comment by ravening** [comment]
> did you run npm install in the MMM-Jast folder?

@jalibu yes i did

**Comment by jalibu** [comment]
please upgrade your magic mirror version. I guess it is too old.
