### ISSUE TITLE
JAST won't load

### ISSUE THREAD

**Issue by TimoFrancke-cnic** [jalibu/MMM-Jast#60]
### Platform

Raspbian GNU/Linux 11 (bullseye)

### Node.js Version

v18.18.0

### MagicMirror Version

2.25.0

### Module Version

v2.8.2

### Description

Module does not allow the whole MagicMirror to load due to an error.

I have tried the test/debugLogging branch but didn't see more details, and I am using the stock config from the Readme. `npm install --only=production` was completed at several points, such as when changing branches. 

### Steps to reproduce

using a fresh config.js file, add the stock config, save, and restart MagicMirror. It results in an error. 

### Log

```shell
0|MagicMir | [32084:1005/115806.659799:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
0|MagicMir | ../../buildtools/third_party/libc++/trunk/include/vector:1473: assertion __n < size() failed: vector[] index out of bounds[32084:1005/115937.268347:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=134
0|MagicMir | [05.10.2023 12:00.58.920] [ERROR] (node:32332) UnhandledPromiseRejectionWarning: SyntaxError: /home/magic/MagicMirror/modules/MMM-Jast/node_modules/tr46/lib/mappingTable.json: Expected ',' or ']' after array element in JSON at position 102912
0|MagicMir |     at parse (<anonymous>)
0|MagicMir |     at Object..json (node:internal/modules/cjs/loader:1340:39)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMir |     at node:internal/modules/cjs/loader:967:12
0|MagicMir |     at Function._load (node:electron/js2c/asar_bundle:2:13327)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:110:18)
0|MagicMir |     at Object.<anonymous> (/home/magic/MagicMirror/modules/MMM-Jast/node_modules/tr46/index.js:4:20)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMir |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMir |     at node:internal/modules/cjs/loader:967:12
0|MagicMir |     at Function._load (node:electron/js2c/asar_bundle:2:13327)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:110:18)
0|MagicMir |     at Object.<anonymous> (/home/magic/MagicMirror/modules/MMM-Jast/node_modules/whatwg-url/lib/url-state-machine.js:3:14)
0|MagicMir | (Use `electron --trace-warnings ...` to show where the warning was created)
0|MagicMir | [05.10.2023 12:00.58.923] [ERROR] (node:32332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|MagicMir | [32332:1005/120100.981088:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

### config.js

```javascript
/* MagicMirror² Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 *
 * You can use environment variables using a `config.js.template` file instead of `config.js`
 * which will be converted to `config.js` while starting. For more information
 * see https://docs.magicmirror.builders/configuration/introduction.html#enviromnent-variables
 */
let config = {
	address: "0.0.0.0",	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/",			// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
					  		// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1","::ffff:192.168.1.0/24"],	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
        {
            module: "MMM-Jast",
            position: "top_left",
            config: {
                currencyStyle: "code", // One of ["code", "symbol", "name"]
                fadeSpeedInSeconds: 3.5,
                lastUpdateFormat: "HH:mm",
                maxChangeAge: 1 * 24 * 60 * 60 * 1000,
                maxWidth: "100%",
                numberDecimalsPercentages: 1,
                numberDecimalsValues: 2,
                scroll: "vertical", // One of ["none", "vertical", "horizontal"]
                showColors: true,
                showCurrency: true,
                showChangePercent: true,
                showChangeValue: false,
                showChangeValueCurrency: false,
                showHiddenStocks: false,
                showLastUpdate: false,
                showPortfolioValue: false,
                showPortfolioGrowthPercent: false,
                showPortfolioGrowth: false,
                updateIntervalInSeconds: 300,
                useGrouping: false,
                virtualHorizontalMultiplier: 2,
                stocks: [
                    { name: "BASF", symbol: "BAS.DE", quantity: 10 },
                    { name: "SAP", symbol: "SAP.DE", quantity: 15 },
                    { name: "Henkel", symbol: "HEN3.DE", hidden: true },
                    { name: "Alibaba", symbol: "BABA"}
                ]
            }
        }
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by jalibu** [comment]
I can't reproduce that

**Comment by sdetweil** [comment]
at grandson school things.  back this afternoon..

**Comment by jalibu** [comment]
@TimoFrancke-cnic I'd recommend to delete the node_modules folder and to execute `npm install` again.

**Comment by sdetweil** [comment]
>: Expected ',' or ']' after array element in JSON at position 102912

just says the content is not as expected. could be network, or server related.. 

still should use try/catch to watch out for these problems
