### ISSUE TITLE
Broken Dependencies after d22f516

### ISSUE THREAD

**Issue by cdemi** [jalibu/MMM-Jast#63]
### Platform

Raspberry Pi OS

### Node.js Version

18.18.0

### MagicMirror Version

2.26.0

### Module Version

ea0289fbc9f5752480d1eb61f2088afc4a95c88f

### Description

When upgrading to the latest version and running npm install:

```
pi@MagicMirror:~/MagicMirror/modules/MMM-Jast $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: mmm-jast@2.9.1
npm ERR! Found: @rollup/plugin-commonjs@20.0.0
npm ERR! node_modules/@rollup/plugin-commonjs
npm ERR!   dev @rollup/plugin-commonjs@"^25.0.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @rollup/plugin-commonjs@"^25.0.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: rollup@4.9.2
npm ERR! node_modules/rollup
npm ERR!   peerOptional rollup@"^2.68.0||^3.0.0||^4.0.0" from @rollup/plugin-commonjs@25.0.7
npm ERR!   node_modules/@rollup/plugin-commonjs
npm ERR!     dev @rollup/plugin-commonjs@"^25.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-debug-0.log
```

### Steps to reproduce

1. git pull
2. npm i

### Log

```shell
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.8.1
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 9ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/pi/MagicMirror/modules/MMM-Jast/.npmrc Completed in 0ms
10 timing config:load:project Completed in 10ms
11 timing config:load:file:/home/pi/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 2ms
15 timing config:load:setEnvs Completed in 4ms
16 timing config:load Completed in 43ms
17 timing npm:load:configload Completed in 44ms
18 timing config:load:flatten Completed in 15ms
19 timing npm:load:mkdirpcache Completed in 2ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm i
22 verbose argv "i"
23 timing npm:load:setTitle Completed in 4ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-
26 verbose logfile /home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-debug-0.log
27 timing npm:load:logFile Completed in 39ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 187ms
31 timing arborist:ctor Completed in 3ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 702ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest yahoo-finance2@^2.9.0
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/yahoo-finance2 410ms (cache hit)
40 silly fetch manifest @rollup/plugin-commonjs@^25.0.7
41 http fetch GET 200 https://registry.npmjs.org/@rollup%2fplugin-commonjs 16ms (cache hit)
42 silly fetch manifest rollup@^4.8.0
43 http fetch GET 200 https://registry.npmjs.org/rollup 42ms (cache hit)
44 silly fetch manifest @rollup/plugin-node-resolve@^15.2.3
45 http fetch GET 200 https://registry.npmjs.org/@rollup%2fplugin-node-resolve 13ms (cache hit)
46 silly fetch manifest @rollup/plugin-terser@^0.4.4
47 http fetch GET 200 https://registry.npmjs.org/@rollup%2fplugin-terser 9ms (cache hit)
48 silly fetch manifest @rollup/plugin-typescript@^11.1.5
49 http fetch GET 200 https://registry.npmjs.org/@rollup%2fplugin-typescript 10ms (cache hit)
50 silly fetch manifest tslib@*
51 http fetch GET 200 https://registry.npmjs.org/tslib 11ms (cache hit)
52 silly fetch manifest typescript@^5.3.3
53 http fetch GET 200 https://registry.npmjs.org/typescript 130ms (cache hit)
54 silly fetch manifest @types/magicmirror-module@^2.16.5
55 http fetch GET 200 https://registry.npmjs.org/@types%2fmagicmirror-module 19ms (cache hit)
56 silly fetch manifest @typescript-eslint/eslint-plugin@^6.14.0
57 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 109ms (cache hit)
58 silly fetch manifest @typescript-eslint/parser@^6.14.0
59 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 131ms (cache hit)
60 silly fetch manifest eslint@^8.55.0
61 http fetch GET 200 https://registry.npmjs.org/eslint 28ms (cache hit)
62 silly fetch manifest eslint-config-prettier@^9.1.0
63 http fetch GET 200 https://registry.npmjs.org/eslint-config-prettier 10ms (cache hit)
64 silly fetch manifest prettier@^3.1.1
65 http fetch GET 200 https://registry.npmjs.org/prettier 10ms (cache hit)
66 timing idealTree Completed in 2546ms
67 timing command:i Completed in 2590ms
68 verbose stack Error: could not resolve
68 verbose stack     at PlaceDep.failPeerConflict (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:503:25)
68 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:157:21)
68 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:933:18)
68 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
68 verbose stack     at async Promise.all (index 1)
68 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
68 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:149:5)
68 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
69 verbose cwd /home/pi/MagicMirror/modules/MMM-Jast
70 verbose Linux 5.10.103-v7l+
71 verbose node v18.18.0
72 verbose npm  v9.8.1
73 error code ERESOLVE
74 error ERESOLVE could not resolve
75 error
76 error While resolving: mmm-jast@2.9.1
76 error Found: @rollup/plugin-commonjs@20.0.0
76 error node_modules/@rollup/plugin-commonjs
76 error   dev @rollup/plugin-commonjs@"^25.0.7" from the root project
76 error
76 error Could not resolve dependency:
76 error dev @rollup/plugin-commonjs@"^25.0.7" from the root project
76 error
76 error Conflicting peer dependency: rollup@4.9.2
76 error node_modules/rollup
76 error   peerOptional rollup@"^2.68.0||^3.0.0||^4.0.0" from @rollup/plugin-commonjs@25.0.7
76 error   node_modules/@rollup/plugin-commonjs
76 error     dev @rollup/plugin-commonjs@"^25.0.7" from the root project
76 error
76 error Fix the upstream dependency conflict, or retry
76 error this command with --force or --legacy-peer-deps
76 error to accept an incorrect (and potentially broken) dependency resolution.
77 error
77 error
77 error For a full report see:
77 error /home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-eresolve-report.txt
78 verbose exit 1
79 timing npm Completed in 3722ms
80 verbose unfinished npm timer reify 1704361802460
81 verbose unfinished npm timer reify:loadTrees 1704361802484
82 verbose unfinished npm timer idealTree:buildDeps 1704361803192
83 verbose unfinished npm timer idealTree:#root 1704361803194
84 verbose code 1
85 error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-01-04T09_50_01_342Z-debug-0.log
```

### config.js

```javascript
doesn't matter
```

**Comment by jalibu** [comment]
Hi @cdemi 
thank you for reporting this.

I wonder how this error can be caused by an update of the MM version.
Actually, an update should not even be necessary.
Have you tried cloning the module again?

**Comment by cdemi** [comment]
Thanks for the tip. Deleting the module and cloning it again worked!

**Comment by cdemi** [comment]
Thanks for the tip. Deleting the module and cloning it again worked!
